/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CourierService } from "../courier.service";
import { CourierCreateInput } from "./CourierCreateInput";
import { Courier } from "./Courier";
import { CourierFindManyArgs } from "./CourierFindManyArgs";
import { CourierWhereUniqueInput } from "./CourierWhereUniqueInput";
import { CourierUpdateInput } from "./CourierUpdateInput";
import { CarFindManyArgs } from "../../car/base/CarFindManyArgs";
import { Car } from "../../car/base/Car";
import { CarWhereUniqueInput } from "../../car/base/CarWhereUniqueInput";

export class CourierControllerBase {
  constructor(protected readonly service: CourierService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Courier })
  async createCourier(
    @common.Body() data: CourierCreateInput
  ): Promise<Courier> {
    return await this.service.createCourier({
      data: {
        ...data,

        office: data.office
          ? {
              connect: data.office,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fullNames: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        password: true,
        personalNumber: true,
        phone: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Courier] })
  @ApiNestedQuery(CourierFindManyArgs)
  async couriers(@common.Req() request: Request): Promise<Courier[]> {
    const args = plainToClass(CourierFindManyArgs, request.query);
    return this.service.couriers({
      ...args,
      select: {
        createdAt: true,
        fullNames: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        password: true,
        personalNumber: true,
        phone: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Courier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async courier(
    @common.Param() params: CourierWhereUniqueInput
  ): Promise<Courier | null> {
    const result = await this.service.courier({
      where: params,
      select: {
        createdAt: true,
        fullNames: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        password: true,
        personalNumber: true,
        phone: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Courier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCourier(
    @common.Param() params: CourierWhereUniqueInput,
    @common.Body() data: CourierUpdateInput
  ): Promise<Courier | null> {
    try {
      return await this.service.updateCourier({
        where: params,
        data: {
          ...data,

          office: data.office
            ? {
                connect: data.office,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fullNames: true,
          id: true,

          office: {
            select: {
              id: true,
            },
          },

          password: true,
          personalNumber: true,
          phone: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Courier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCourier(
    @common.Param() params: CourierWhereUniqueInput
  ): Promise<Courier | null> {
    try {
      return await this.service.deleteCourier({
        where: params,
        select: {
          createdAt: true,
          fullNames: true,
          id: true,

          office: {
            select: {
              id: true,
            },
          },

          password: true,
          personalNumber: true,
          phone: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cars")
  @ApiNestedQuery(CarFindManyArgs)
  async findCars(
    @common.Req() request: Request,
    @common.Param() params: CourierWhereUniqueInput
  ): Promise<Car[]> {
    const query = plainToClass(CarFindManyArgs, request.query);
    const results = await this.service.findCars(params.id, {
      ...query,
      select: {
        courier: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fuelConsumption: true,
        id: true,
        make: true,
        model: true,

        office: {
          select: {
            id: true,
          },
        },

        registrationNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cars")
  async connectCars(
    @common.Param() params: CourierWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        connect: body,
      },
    };
    await this.service.updateCourier({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cars")
  async updateCars(
    @common.Param() params: CourierWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        set: body,
      },
    };
    await this.service.updateCourier({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cars")
  async disconnectCars(
    @common.Param() params: CourierWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        disconnect: body,
      },
    };
    await this.service.updateCourier({
      where: params,
      data,
      select: { id: true },
    });
  }
}
